{
 "title": "LifePO4 SolarShed",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hostname",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "node_uname_info" }
   ]
  },
  {
   "title": "Domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "node_uname_info" }
   ]
  },
  {
   "title": "OS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "node_uname_info" }
   ]
  },
  {
   "title": "Netif Name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "node_network_info" }
   ]
  },
  {
   "title": "IF Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "node_network_info" }
   ]
  },
  {
   "title": "Local Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Stats",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {mountpoint=\"/\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Load 1min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 3 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds)",
     "legendFormat": "InOctets"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{mode='system'}) by (cpu))",
     "legendFormat": "CPU Count"
    }
   ]
  },
  {
   "title": "Procs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "CPU Count" }
   ]
  },
  {
   "title": "Solar Installation",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "AB_SolarStats{myVar=\"unitName\"}"
    }
   ]
  },
  {
   "title": "QC Solar Shed",
   "type": "text",
   "gridPos": { "h": 8, "w": 3, "x": 2, "y": 5 },
   "content": "<img src=http://inetd.com/QC/cam.jpg?123456789134567>",
   "targets": [
    { "expr": "AA_batVolts", "legendFormat": "Battery Volts" },
    { "expr": "AA_pvWatts", "legendFormat": "Watts" },
    { "expr": "AA_batSOC", "legendFormat": "SOC" },
    { "expr": "AA_pvVolts", "legendFormat": "PV Volts" }
   ]
  },
  {
   "title": "Battery SOC",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"batSOC\"}"
    }
   ]
  },
  {
   "title": "PV Volts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"pvVolts\"}"
    }
   ]
  },
  {
   "title": "Generated Today",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"genWatts\"}"
    }
   ]
  },
  {
   "title": "Load Watts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"loadWatts\"}"
    }
   ]
  },
  {
   "title": "Battery Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"batTemp\"}"
    }
   ]
  },
  {
   "title": "Average Cell Voltage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"batVolts\"} / 8"
    }
   ]
  },
  {
   "title": "Min Cell Voltage ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(BMS_A{mode=~\"CellNum.*\"})"
    }
   ]
  },
  {
   "title": "PV Watts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"pvWatts\"}"
    }
   ]
  },
  {
   "title": "Battery Active State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "BMS_A{mode=\"modeInt\"}"
    }
   ]
  },
  {
   "title": "PV Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "AB_SolarStats{myVar=\"sysStatus\"}"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"batVolts\"}"
    }
   ]
  },
  {
   "title": "PV Watts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"pvWatts\"}"
    }
   ]
  },
  {
   "title": "Consumed Power",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"conWatts\"}"
    }
   ]
  },
  {
   "title": "Solar Power Potential",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"pvWatts\"} / 10 *.95"
    }
   ]
  },
  {
   "title": "Inverter Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"devTemp\"}"
    }
   ]
  },
  {
   "title": " Cell Voltage Diff",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 * (max(BMS_A{mode=~\"CellNum.*\"}) - min(BMS_A{mode=~\"CellNum.*\"}))"
    }
   ]
  },
  {
   "title": "Max Cell Voltage ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(BMS_A{mode=~\"CellNum.*\"})"
    }
   ]
  },
  {
   "title": "Charge Mode",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "AB_SolarStats{myVar=\"chargeStatStr\"}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 11 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"pvWatts\"}"
    }
   ]
  },
  {
   "title": "Solar Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"pvWatts\"}",
     "legendFormat": "PV Watts"
    },
    {
     "expr": "AB_SolarStats{mode=\"pvVolts\"}",
     "legendFormat": "PV Volts"
    },
    {
     "expr": "AB_SolarStats{mode=\"pvWatts\"} offset 24h",
     "legendFormat": "PV Watts yesterday"
    }
   ]
  },
  {
   "title": "Solar Stats",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"pvWatts\"}",
     "legendFormat": "PV Watts"
    },
    {
     "expr": "AB_SolarStats{mode=\"pvVolts\"}",
     "legendFormat": "PV Volts"
    },
    {
     "expr": "AB_SolarStats{mode=\"pvWatts\"} offset 24h",
     "legendFormat": "PV Watts yesterday"
    }
   ]
  },
  {
   "title": "Absolute Cell voltages 1-8",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "BMS_A{mode=\"CellNum1\"}",
     "legendFormat": "Cell #1"
    },
    {
     "expr": "BMS_A{mode=\"CellNum2\"}",
     "legendFormat": "Cell #2"
    },
    {
     "expr": "BMS_A{mode=\"CellNum3\"}",
     "legendFormat": "Cell #3"
    },
    {
     "expr": "BMS_A{mode=\"CellNum4\"}",
     "legendFormat": "Cell #4"
    },
    {
     "expr": "BMS_A{mode=\"CellNum5\"}",
     "legendFormat": "Cell #5"
    },
    {
     "expr": "BMS_A{mode=\"CellNum6\"}",
     "legendFormat": "Cell #6"
    },
    {
     "expr": "BMS_A{mode=\"CellNum7\"}",
     "legendFormat": "Cell #7"
    },
    {
     "expr": "BMS_A{mode=\"CellNum8\"}",
     "legendFormat": "Cell #8"
    }
   ]
  },
  {
   "title": "Absolute Cell voltages 1-8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BMS_A{mode=\"CellNum1\"}",
     "legendFormat": "Cell #1"
    },
    {
     "expr": "BMS_A{mode=\"CellNum2\"}",
     "legendFormat": "Cell #2"
    },
    {
     "expr": "BMS_A{mode=\"CellNum3\"}",
     "legendFormat": "Cell #3"
    },
    {
     "expr": "BMS_A{mode=\"CellNum4\"}",
     "legendFormat": "Cell #4"
    },
    {
     "expr": "BMS_A{mode=\"CellNum5\"}",
     "legendFormat": "Cell #5"
    },
    {
     "expr": "BMS_A{mode=\"CellNum6\"}",
     "legendFormat": "Cell #6"
    },
    {
     "expr": "BMS_A{mode=\"CellNum7\"}",
     "legendFormat": "Cell #7"
    },
    {
     "expr": "BMS_A{mode=\"CellNum8\"}",
     "legendFormat": "Cell #8"
    }
   ]
  },
  {
   "title": "Battery Current Flow (amps)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "BMS_A{mode=\"current\"}",
     "legendFormat": "Current I/O"
    },
    {
     "expr": "BMS_A{mode=\"current\"} offset 24h",
     "legendFormat": "Yesterday"
    }
   ]
  },
  {
   "title": "Battery Active State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "BMS_A{mode=\"modeInt\"}"
    }
   ]
  },
  {
   "title": "Current Flow Rate (amps)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BMS_A{mode=\"current\"}"
    }
   ]
  },
  {
   "title": " Cell MilliVolt Spread",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1000 * (max(BMS_A{mode=~\"CellNum.*\"}) - min(BMS_A{mode=~\"CellNum.*\"}))",
     "legendFormat": "Cell Spread"
    }
   ]
  },
  {
   "title": " Cell MilliVolt Spread",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 * (max(BMS_A{mode=~\"CellNum.*\"}) - min(BMS_A{mode=~\"CellNum.*\"}))"
    }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"batVolts\"}",
     "legendFormat": "Battery Volts"
    },
    {
     "expr": "AB_SolarStats{mode=\"batVolts\"} offset 24h",
     "legendFormat": "Battery Volts Yesterday"
    }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"batVolts\"}",
     "legendFormat": "Battery Volts"
    },
    {
     "expr": "AB_SolarStats{mode=\"batVolts\"} offset 24h",
     "legendFormat": "Battery Volts Yesterday"
    }
   ]
  },
  {
   "title": "Battery SOC",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"batSOC\"}",
     "legendFormat": "Battery SOC"
    },
    {
     "expr": "AB_SolarStats{mode=\"batSOC\"} offset 24h",
     "legendFormat": "Yesterday"
    }
   ]
  },
  {
   "title": "Battery SOC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"batSOC\"}",
     "legendFormat": "Battery SOC"
    },
    {
     "expr": "AB_SolarStats{mode=\"batSOC\"} offset 24h",
     "legendFormat": "Yesterday"
    }
   ]
  },
  {
   "title": "Charging  Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none", "label": "Status" }
   ],
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"chargeStatVal\"}",
     "legendFormat": "Charging Status"
    },
    {
     "expr": "AB_SolarStats{mode=\"chargeStatVal\"} offset 24h",
     "legendFormat": "Yesterday"
    }
   ]
  },
  {
   "title": "Charge Mode",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 50 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "AB_SolarStats{myVar=\"chargeStatStr\"}"
    }
   ]
  },
  {
   "title": "System Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"batTemp\"}",
     "legendFormat": "Edecoa 3500w AC Inverter"
    },
    {
     "expr": "AB_SolarStats{mode=\"devTemp\"}",
     "legendFormat": "EPEVER MPPT Charge Controller"
    },
    {
     "expr": "AB_SolarStats{mode=\"devTemp\"} offset 24h",
     "legendFormat": "Charge Controller yesterday"
    },
    {
     "expr": "AB_SolarStats{mode=\"batTemp\"} offset 24h",
     "legendFormat": "Inverter  yesterday"
    }
   ]
  },
  {
   "title": "System Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"batTemp\"}",
     "legendFormat": "Edecoa Inverter"
    },
    {
     "expr": "AB_SolarStats{mode=\"devTemp\"}",
     "legendFormat": "Epever  MPPT"
    },
    {
     "expr": "AB_SolarStats{mode=\"devTemp\"} offset 24h",
     "legendFormat": "Epever yesterday"
    },
    {
     "expr": "AB_SolarStats{mode=\"batTemp\"} offset 24h",
     "legendFormat": "Edecoa yesterday"
    }
   ]
  },
  {
   "title": "BMS Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "BMS_A{mode=\"temp1\"}",
     "legendFormat": "BMS heatsink"
    },
    {
     "expr": "BMS_A{mode=\"temp2\"}",
     "legendFormat": "Ambient"
    },
    {
     "expr": "BMS_A{mode=\"temp1\"} offset 24h",
     "legendFormat": "BMS heatsink yesterday"
    },
    {
     "expr": "BMS_A{mode=\"temp2\"} offset 24h",
     "legendFormat": "Ambient yesterday"
    }
   ]
  },
  {
   "title": "System Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BMS_A{mode=\"temp1\"}",
     "legendFormat": "BMS Heatsink"
    },
    {
     "expr": "BMS_A{mode=\"temp2\"}",
     "legendFormat": "Ambient"
    },
    {
     "expr": "BMS_A{mode=\"temp1\"} offset 24h",
     "legendFormat": "BMS yesterday"
    },
    {
     "expr": "BMS_A{mode=\"temp2\"} offset 24h",
     "legendFormat": "Ambient yesterday"
    }
   ]
  },
  {
   "title": "Load Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"loadCurr\"}",
     "legendFormat": "Amps"
    },
    {
     "expr": "AB_SolarStats{mode=\"loadWatts\"}",
     "legendFormat": "Watts"
    },
    {
     "expr": "AB_SolarStats{mode=\"loadVolts\"}",
     "legendFormat": "Volts"
    }
   ]
  },
  {
   "title": "Load Stats",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"loadCurr\"}",
     "legendFormat": "Amps"
    },
    {
     "expr": "AB_SolarStats{mode=\"loadWatts\"}",
     "legendFormat": "Watts"
    },
    {
     "expr": "AB_SolarStats{mode=\"loadVolts\"}",
     "legendFormat": "Volts"
    }
   ]
  },
  {
   "title": "Power Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "Watts" }
   ],
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"genWatts\"}",
     "legendFormat": "Generated Today"
    },
    {
     "expr": "AB_SolarStats{mode=\"conWatts\"}",
     "legendFormat": "Consumed Today"
    },
    {
     "expr": "AB_SolarStats{mode=\"genWatts\"} Offset 24h",
     "legendFormat": "Generated Yesterday"
    }
   ]
  },
  {
   "title": "Power Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AB_SolarStats{mode=\"genWatts\"}",
     "legendFormat": "Generated Today"
    },
    {
     "expr": "AB_SolarStats{mode=\"conWatts\"}",
     "legendFormat": "Consumed Today"
    }
   ]
  }
 ]
}