{
 "title": "Solar Battery - Renogy 12v LifePo4 4S1P",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Solar Wyze Camera Report",
   "type": "text",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "\n<H2> LifePO4 4s 12v Solar Battery for Wyze camera USB power</H2>\n\nWyze Camera system consisting of 4 6ah LifePo4 cells. </LI>\n  <LI>1 x 20W panel</LI>\n  <LI>DALY 30A 12V BMS></LI>\n  <LI>Renogy Wanderer 10a Li solar charger</LI>\n  <LI>Raspberry Pi Zero connected via RS232</LI>\n  <LI>DHT-11 Temp/Humidity Sensor</LI>\n  <LI>Reporting via Prometheus and Grafana 7</LI>\n\n\n\n\n"
   }
  },
  {
   "title": "Pi System",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {mountpoint=\"/\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Pi 1 Minute Load Avg",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "12hr Power In",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(avg_over_time(Renogy{mode=\"pvWatts\"}[12h])) * 12",
     "legendFormat": "Power In"
    }
   ]
  },
  {
   "title": "12HrPower Out",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(avg_over_time(Renogy{mode=\"loadWatts\"}[12h])) * 12",
     "legendFormat": "Power Out"
    }
   ]
  },
  {
   "title": "Todays Max Charge Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "Renogy{mode=\"todayChgPwr\"}",
     "legendFormat": "Todays Power"
    }
   ]
  },
  {
   "title": "Todays Max Discharge Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "Renogy{mode=\"todayDischgPwr\"}",
     "legendFormat": "Todays Power"
    }
   ]
  },
  {
   "title": "System Up Days",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "Renogy{mode=\"upDays\"}",
     "legendFormat": "upDays"
    }
   ]
  },
  {
   "title": "State of Charge",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "Renogy{mode=\"SOC\"}",
     "legendFormat": "SOC"
    }
   ]
  },
  {
   "title": "State of Charge",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "Renogy{mode=\"SOC\"}",
     "legendFormat": "SOC"
    }
   ]
  },
  {
   "title": "Current Flow (Watts)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "expr": "Renogy{mode=\"pvWatts\"}",
     "legendFormat": "Power In (W)"
    },
    {
     "expr": "Renogy{mode=\"pvWatts\"} offset 24h",
     "legendFormat": "Yesterday"
    },
    {
     "expr": "Renogy{mode=\"loadWatts\"}",
     "legendFormat": "Power Out (W)"
    },
    {
     "expr": "Renogy{mode=\"loadWatts\"} offset 24h",
     "legendFormat": "Yesterday"
    }
   ]
  },
  {
   "title": "Current Flow",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "Renogy{mode=\"pvAmps\"} * ignoring(mode) Renogy{mode=\"batVolts\"}",
     "legendFormat": "Power In"
    },
    {
     "expr": "Renogy{mode=\"loadWatts\"}",
     "legendFormat": "Power Out"
    }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "volt", "label": "Volts" }
   ],
   "targets": [
    {
     "expr": "Renogy{mode=\"batVolts\"}",
     "legendFormat": "Battery Voltage"
    },
    {
     "expr": "Renogy{mode=\"batVolts\"} offset 24h",
     "legendFormat": "Yesterday"
    }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "Renogy{mode=\"batVolts\"}",
     "legendFormat": "Battery Voltage"
    },
    {
     "expr": "Renogy{mode=\"batVolts\"} / 4",
     "legendFormat": "Avg Cell Voltage"
    }
   ]
  },
  {
   "title": "PV Volts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "volt", "label": "Volts" }
   ],
   "targets": [
    {
     "expr": "Renogy{mode=\"pvVolts\"}",
     "legendFormat": "Battery Voltage"
    },
    {
     "expr": "Renogy{mode=\"pvVolts\"} offset 24h",
     "legendFormat": "Yesterday"
    }
   ]
  },
  {
   "title": "PV Volts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "Renogy{mode=\"pvVolts\"}",
     "legendFormat": "PV Voltage"
    }
   ]
  },
  {
   "title": "Charge State",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "State" }
   ],
   "targets": [
    {
     "expr": "Renogy{mode=\"chargeState\"}",
     "legendFormat": "Charger State"
    },
    {
     "expr": "Renogy{mode=\"chargeState\"} offset 24h",
     "legendFormat": "Yesterday"
    }
   ]
  },
  {
   "title": "SCC State",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "Renogy{mode=\"chargeState\"}",
     "legendFormat": "Charge State"
    }
   ]
  },
  {
   "title": "SCC Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Renogy{mode=\"sccTemp\"}",
     "legendFormat": "SCC Temp"
    },
    {
     "expr": "Renogy{mode=\"sccTemp\"} offset 24h",
     "legendFormat": "Yesterday"
    }
   ]
  },
  {
   "title": "SCC Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "Renogy{mode=\"sccTemp\"}",
     "legendFormat": "SCC Temp"
    }
   ]
  },
  {
   "title": "Ext Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(QC_power{mode=\"totalWatts\"}[24h]) / 1000) * 24",
     "legendFormat": "Ext Temp"
    },
    {
     "expr": "DHT11{mode=\"sysTemp\"} offset 24h",
     "legendFormat": "Yesterday"
    }
   ]
  },
  {
   "title": "External Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "DHT11{mode=\"sysTemp\"}",
     "legendFormat": "Ext Temp"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DHT11{mode=\"sysHumid\"}",
     "legendFormat": "Humidity"
    },
    {
     "expr": "DHT11{mode=\"sysHumid\"} offset 24h",
     "legendFormat": "Yesterday"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "DHT11{mode=\"sysHumid\"}",
     "legendFormat": "Humidity"
    }
   ]
  }
 ]
}