{
 "title": "MPP3048 BYD Split Phase",
 "description": "2 x MPP3048 Split Phase 16S2P BYD 7.kwh",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Solar Config",
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "\n# MPP 3048 Split phase pair\n48v 16P2S LifePO4\n\n"
   }
  },
  {
   "title": "PiZero System",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {mountpoint=\"/\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
     "legendFormat": "Swap"
    }
   ]
  },
  { "title": "Solar Power", "type": "innius-video-panel", "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 } },
  {
   "title": "QC Solar Shed",
   "type": "dalvany-image-panel",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "targets": [
    { "expr": "node_context_switches_total" }
   ]
  },
  {
   "title": "PiZero Load Avg",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "Hostname",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "node_uname_info" }
   ]
  },
  {
   "title": "Domain",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "node_uname_info" }
   ]
  },
  {
   "title": "Fault Mode",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"faultCode\"}",
     "legendFormat": "Fault Code"
    }
   ]
  },
  {
   "title": "Work Mode",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"workMode\"}",
     "legendFormat": "Work Mode"
    }
   ]
  },
  {
   "title": "Source Mode",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"srcMode\"}",
     "legendFormat": "Work Mode"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds)",
     "legendFormat": "InOctets"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"acCharging\"}",
     "legendFormat": "AC Charging "
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"acLoadOn\"}",
     "legendFormat": "AC Load On"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"acLost\"}",
     "legendFormat": "AC Lost"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"batUnderV\"}",
     "legendFormat": "Battery UV"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"batOverV\"}",
     "legendFormat": "Battery OV"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"sccCharging\"}",
     "legendFormat": "SCC Charging"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"sccOK\"}",
     "legendFormat": "SCC OK"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"confChange\"}",
     "legendFormat": "Config Change"
    }
   ]
  },
  {
   "title": "Battery SOC",
   "type": "graph",
   "description": "SOC",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"batCap\"}",
     "legendFormat": "SCC SOC"
    },
    {
     "expr": "MPP3048_P1{mode=\"batCap\"} offset 24h",
     "legendFormat": "SCC Yesterday"
    },
    {
     "expr": "BMS_A{mode=\"SOC\"}",
     "legendFormat": "BMS SOC"
    },
    {
     "expr": "BMS_A{mode=\"SOC\"} offset 24h",
     "legendFormat": "BMS Yesterday"
    }
   ]
  },
  {
   "title": "Battery SOC ",
   "type": "gauge",
   "description": "SOC & BMS",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"batCap\"}",
     "legendFormat": "SCC "
    },
    {
     "expr": "MPP3048_P1{mode=\"batCap\"} offset 24h",
     "legendFormat": "SCC Yesterday "
    },
    {
     "expr": "BMS_A{mode=\"SOC\"}",
     "legendFormat": "BMS SOC "
    },
    {
     "expr": "BMS_A{mode=\"SOC\"} offset 24h",
     "legendFormat": "BMS Yesterday "
    }
   ]
  },
  {
   "title": "PV Watts",
   "type": "graph",
   "description": "P1 and P2 panel Watts",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"pvWatts\"}",
     "legendFormat": "P1 PV Watts"
    },
    {
     "expr": "MPP3048_P2{mode=\"pvWatts\"}",
     "legendFormat": "P2 PV Watts"
    },
    {
     "expr": "MPP3048_P1{mode=\"pvWatts\"} + MPP3048_P2{mode=\"pvWatts\"}",
     "legendFormat": "Total Watts"
    },
    {
     "expr": "MPP3048_P1{mode=\"pvWatts\"} offset 24h + MPP3048_P2{mode=\"pvWatts\"} offset 24h",
     "legendFormat": "Yesterday"
    }
   ]
  },
  {
   "title": "PV Power Watts",
   "type": "gauge",
   "description": "P1 and P2 panel Watts",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"pvWatts\"}",
     "legendFormat": "P1 PV Watts"
    },
    {
     "expr": "MPP3048_P2{mode=\"pvWatts\"}",
     "legendFormat": "P2 PV Watts"
    },
    {
     "expr": "MPP3048_P2{mode=\"pvWatts\"} + MPP3048_P1{mode=\"pvWatts\"}",
     "legendFormat": "Total Watts"
    }
   ]
  },
  {
   "title": "PV Voltage",
   "type": "graph",
   "description": "P1 and P2 panel voltage",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"pvVolts\"}",
     "legendFormat": "P1 PV Volts"
    },
    {
     "expr": "MPP3048_P2{mode=\"pvVolts\"}",
     "legendFormat": "P2 PV Volts"
    }
   ]
  },
  {
   "title": "PV Voltage",
   "type": "gauge",
   "description": "P1 and P2 panel voltage",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"pvVolts\"}",
     "legendFormat": "P1 PV voltage"
    },
    {
     "expr": "MPP3048_P2{mode=\"pvVolts\"}",
     "legendFormat": "P2 PV voltage"
    }
   ]
  },
  {
   "title": "Realtime Cell Voltages",
   "type": "bargauge",
   "description": "volts",
   "gridPos": { "h": 22, "w": 7, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "BMS_A{mode=\"CellNum1\"}",
     "legendFormat": "Cell 1"
    },
    {
     "expr": "BMS_A{mode=\"CellNum2\"}",
     "legendFormat": "Cell 2"
    },
    {
     "expr": "BMS_A{mode=\"CellNum3\"}",
     "legendFormat": "Cell 3"
    },
    {
     "expr": "BMS_A{mode=\"CellNum4\"}",
     "legendFormat": "Cell 4"
    },
    {
     "expr": "BMS_A{mode=\"CellNum4\"}",
     "legendFormat": "Cell 4"
    },
    {
     "expr": "BMS_A{mode=\"CellNum5\"}",
     "legendFormat": "Cell 5"
    },
    {
     "expr": "BMS_A{mode=\"CellNum6\"}",
     "legendFormat": "Cell 6"
    },
    {
     "expr": "BMS_A{mode=\"CellNum7\"}",
     "legendFormat": "Cell 7"
    },
    {
     "expr": "BMS_A{mode=\"CellNum8\"}",
     "legendFormat": "Cell 8"
    },
    {
     "expr": "BMS_A{mode=\"CellNum9\"}",
     "legendFormat": "Cell 9"
    },
    {
     "expr": "BMS_A{mode=\"CellNum10\"}",
     "legendFormat": "Cell 10"
    },
    {
     "expr": "BMS_A{mode=\"CellNum11\"}",
     "legendFormat": "Cell 11"
    },
    {
     "expr": "BMS_A{mode=\"CellNum12\"}",
     "legendFormat": "Cell 12"
    },
    {
     "expr": "BMS_A{mode=\"CellNum13\"}",
     "legendFormat": "Cell 13"
    },
    {
     "expr": "BMS_A{mode=\"CellNum14\"}",
     "legendFormat": "Cell 14"
    },
    {
     "expr": "BMS_A{mode=\"CellNum15\"}",
     "legendFormat": "Cell 15"
    },
    {
     "expr": "BMS_A{mode=\"CellNum16\"}",
     "legendFormat": "Cell 16"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "description": "volts",
   "gridPos": { "h": 6, "w": 11, "x": 7, "y": 31 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"batVolts\"}",
     "legendFormat": "P1 Battery Voltage"
    },
    {
     "expr": "MPP3048_P2{mode=\"batVolts\"}",
     "legendFormat": "P2 Battery Voltage"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "description": "P1 and P2 battery voltage",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"batVolts\"}",
     "legendFormat": "P1 Battery Voltage"
    },
    {
     "expr": "MPP3048_P2{mode=\"batVolts\"}",
     "legendFormat": "P2 Battery Voltage"
    }
   ]
  },
  {
   "title": "LifePo4 Cell Voltages",
   "type": "gauge",
   "description": "P1 and P2 battery voltage",
   "gridPos": { "h": 9, "w": 5, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(BMS_A{mode=~\"CellNum.*\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "max(BMS_A{mode=~\"CellNum.*\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(BMS_A{mode=~\"CellNum.*\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "1000 * (max(BMS_A{mode=~\"Cell.*\"}) - min(BMS_A{mode=~\"Cell.*\"}))",
     "legendFormat": "Spread (mv)"
    }
   ]
  },
  {
   "title": "Cell Voltages",
   "type": "graph",
   "description": "volts",
   "gridPos": { "h": 8, "w": 11, "x": 7, "y": 37 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "BMS_A{mode=\"CellNum1\"}",
     "legendFormat": "Cell 1"
    },
    {
     "expr": "BMS_A{mode=\"CellNum2\"}",
     "legendFormat": "Cell 2"
    },
    {
     "expr": "BMS_A{mode=\"CellNum3\"}",
     "legendFormat": "Cell 3"
    },
    {
     "expr": "BMS_A{mode=\"CellNum4\"}",
     "legendFormat": "Cell 4"
    },
    {
     "expr": "BMS_A{mode=\"CellNum4\"}",
     "legendFormat": "Cell 4"
    },
    {
     "expr": "BMS_A{mode=\"CellNum5\"}",
     "legendFormat": "Cell 5"
    },
    {
     "expr": "BMS_A{mode=\"CellNum6\"}",
     "legendFormat": "Cell 6"
    },
    {
     "expr": "BMS_A{mode=\"CellNum7\"}",
     "legendFormat": "Cell 7"
    },
    {
     "expr": "BMS_A{mode=\"CellNum8\"}",
     "legendFormat": "Cell 8"
    },
    {
     "expr": "BMS_A{mode=\"CellNum9\"}",
     "legendFormat": "Cell 9"
    },
    {
     "expr": "BMS_A{mode=\"CellNum10\"}",
     "legendFormat": "Cell 10"
    },
    {
     "expr": "BMS_A{mode=\"CellNum11\"}",
     "legendFormat": "Cell 11"
    },
    {
     "expr": "BMS_A{mode=\"CellNum12\"}",
     "legendFormat": "Cell 12"
    },
    {
     "expr": "BMS_A{mode=\"CellNum13\"}",
     "legendFormat": "Cell 13"
    },
    {
     "expr": "BMS_A{mode=\"CellNum14\"}",
     "legendFormat": "Cell 14"
    },
    {
     "expr": "BMS_A{mode=\"CellNum15\"}",
     "legendFormat": "Cell 15"
    },
    {
     "expr": "BMS_A{mode=\"CellNum16\"}",
     "legendFormat": "Cell 16"
    }
   ]
  },
  {
   "title": "Cell Spread (mv)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 7, "y": 45 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "1000 * (max(BMS_A{mode=~\"Cell.*\"}) - min(BMS_A{mode=~\"Cell.*\"}))",
     "legendFormat": "Cell Spread (mv)"
    },
    {
     "expr": "1000 * (max(BMS_A{mode=~\"Cell.*\"} offset 24h) - min(BMS_A{mode=~\"Cell.*\"} offset 24h))",
     "legendFormat": "Yesterday"
    }
   ]
  },
  {
   "title": "Cell Spread (mv)",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "format": "mvolt",
   "targets": [
    {
     "expr": "1000 * (max(BMS_A{mode=~\"Cell.*\"}) - min(BMS_A{mode=~\"Cell.*\"}))",
     "legendFormat": "Spread (mv)"
    }
   ]
  },
  {
   "title": "AC Load %",
   "type": "graph",
   "description": "P1 and P2 AC Load",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"acLoadPC\"}",
     "legendFormat": "P1 AC Load %"
    },
    {
     "expr": "MPP3048_P2{mode=\"acLoadPC\"}",
     "legendFormat": "P2 AC Load %"
    }
   ]
  },
  {
   "title": "AC Power Load %",
   "type": "gauge",
   "description": "P1 and P2 AC Load %",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"acLoadPC\"}",
     "legendFormat": "P1 AC Load %"
    },
    {
     "expr": "MPP3048_P2{mode=\"acLoadPC\"}",
     "legendFormat": "P2 AC Load %"
    },
    {
     "expr": "( MPP3048_P1{mode=\"acLoadPC\"} + MPP3048_P2{mode=\"acLoadPC\"} ) / 2",
     "legendFormat": "Total System Load"
    }
   ]
  },
  {
   "title": "AC Watts",
   "type": "graph",
   "description": "P1 and P2 AC Watts",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"acWatts\"}",
     "legendFormat": "P1 AC Watts"
    },
    {
     "expr": "MPP3048_P2{mode=\"acWatts\"}",
     "legendFormat": "P2 AC Watts"
    }
   ]
  },
  {
   "title": "AC Power Watts",
   "type": "gauge",
   "description": "P1 and P2 panel Watts",
   "gridPos": { "h": 10, "w": 5, "x": 18, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"acWatts\"}",
     "legendFormat": "P1 AC Watts"
    },
    {
     "expr": "MPP3048_P2{mode=\"acWatts\"}",
     "legendFormat": "P2 AC Watts"
    },
    {
     "expr": "MPP3048_P1{mode=\"acWatts\"} + MPP3048_P2{mode=\"acWatts\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Grid Voltage",
   "type": "graph",
   "description": "detected by P1 and P2",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"gridVolts\"}",
     "legendFormat": "P1 Grid Voltage"
    },
    {
     "expr": "MPP3048_P2{mode=\"gridVolts\"}",
     "legendFormat": "P2 Grid Voltage"
    }
   ]
  },
  {
   "title": "Grid Voltage",
   "type": "gauge",
   "description": "detected by P1 and P2",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MPP3048_P1{mode=\"gridVolts\"}",
     "legendFormat": "P1 Grid Volts"
    },
    {
     "expr": "MPP3048_P2{mode=\"gridVolts\"}",
     "legendFormat": "P2 Grid Volts"
    }
   ]
  }
 ]
}